#!/bin/bash
if [ $# -eq 0 ]
then
    python3 ~/.python-color/cmdline.py
else
    if [ $1 == "uninstall" ]
    then
        printf "Are you sure you want to uninstall python-color? (y/n): "
        read shouldUninstall
        if [ $shouldUninstall == "y" ]
        then
            echo "Uninstalling..."
            rm ../.python-color
            echo -e "\033[31m\033[1mpython-color has been uninstalled\033[0m"
            echo -e "\033[31m\033[1mPlease remember to remove the python-color from your PATH\033[0m"
        fi
    fi
fi